### ISSUE TITLE
On Save Tracking - export version log

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/Autoscoper#214]
In an effort to document now for future users of datatsets:

- [ ] enable , on saveTracking a log which includes
    - [ ]  hardware specs of machine
    - [ ]  aut / slicer version

**Comment by amymmorton** [comment]
close in favor of #252
